import{a as w,S as C,i as l}from"./assets/vendor-f736e62a.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const t of o)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(o){const t={};return o.integrity&&(t.integrity=o.integrity),o.referrerPolicy&&(t.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?t.credentials="include":o.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(o){if(o.ep)return;o.ep=!0;const t=s(o);fetch(o.href,t)}})();let g=15;async function P(){let e;a===1?e=h.elements.search.value.trim().split(" ").join("+"):e=y.trim().split(" ").join("+");const r=new URLSearchParams({key:"43219571-0a26e2304ee50d7f75a2b614a",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:g});return(await w.get(`https://pixabay.com/api/?${r}`)).data}const u=document.querySelector(".gallery"),S=new C(".gallery a",{captionsData:"alt",captionDelay:250});function v(e){const r=e.map(({largeImageURL:s,webformatURL:i,tags:o,likes:t,views:n,comments:L,downloads:B})=>`<li class="photos-list-item">
            <a class="photos-list-link" href="${s}">
            <img class="photo" src="${i}" alt="${o}"/>
            </a>
            <ul class="photo-information-container">
            <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${t}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${n}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${L}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${B}</p></li>
            </ul>
            </li>`).join("");u.insertAdjacentHTML("beforeend",r),S.refresh()}const h=document.querySelector(".search-form");let a=1,y="",m=1;const c=document.querySelector(".load-more-btn");p(c);const d=document.querySelector(".loader");p(d);window.onload=F;h.addEventListener("submit",E);c.addEventListener("click",$);function E(e){e.preventDefault(),u.innerHTML="";const r=e.target.elements.search.value.trim();if(r!=="")a=1,y=r,b();else return l.show({theme:"dark",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",message:"Please complete the field!",messageColor:"#FAFAFB",position:"topRight"})}async function b(){try{if(p(c),f(d),a<=m){const e=await P();if(e.totalHits!=0){m=Math.ceil(e.totalHits/g),v(e.hits);const s=u.querySelector(".photos-list-item").getBoundingClientRect();window.scrollBy({top:s.height*2,behavior:"smooth"}),a<m?f(c):l.info({theme:"dark",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",message:"We're sorry, there are no more images to load",messageColor:"#FAFAFB",position:"topRight"})}else l.error({theme:"dark",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FAFAFB",position:"topRight"})}}catch(e){console.log(e),l.error({message:`${e.message}`,theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}finally{p(d),F(),h.reset()}}function $(){++a,b()}function f(e){e.classList.remove("hidden"),e.style.display="flex"}function p(e){e.classList.add("hidden"),e.style.display="none"}function F(){document.body.classList.add("loaded"),document.body.classList.remove("loaded_hiding")}
//# sourceMappingURL=commonHelpers.js.map
